version: '2'
services:
    ustxblog-app:
        image: ustxblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ustxblog-mysql:3306/ustxblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ustxblog-mysql:
        extends:
            file: mysql.yml
            service: ustxblog-mysql
